### PR TITLE
chore: Replace most usages of "which" with "that"

### PR DESCRIPTION
**Pull request by stephenwade**
I noticed some bad grammar in the DefinitelyTyped repo comments, so I've created this PR to fix it.

Most places in this code that use "which" should use "that". "that" is used in restrictive clauses, and "which" is used in nonrestrictive clauses.

More info about the grammar: https://www.dictionary.com/e/that-vs-which/

### CODE REVIEW

**Comment by jakebailey** [comment]
Not sure why this didn't fail before, but all of the baselines that include this text have to be updated to be passing.

**Comment by stephenwade** [comment]
@jakebailey I updated the baselines with `npm test -- -u`.

**Comment by jakebailey** [comment]
I think you missed merging from master before that, sorry!

**Comment by stephenwade** [comment]
@jakebailey How's this?

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
