### PR TITLE
Remove tslint

### PR DESCRIPTION
**Pull request by sandersn**
And do not add checking for eslint. Not sure that's the right choice.

OTHER_FILES.txt also isn't checked anymore. Also there are some unused link constants.

### CODE REVIEW

**Comment by sandersn** [comment]
@JoshuaKGoldberg you are probably interested in this too.

**Comment by JoshuaKGoldberg** [comment]
👍 this is of interest to me, thanks for the ping! I don't have anything to add but I am very happy about it. 🙂

**Review by jakebailey — APPROVED** [review]
LGTM but I think we'll have to remove tslint.json from the repo first as we'll now treat them as infrastructure and nobody's PRs will be mergable.

**Comment by jakebailey** [comment]
Or maybe we are forced to leave it, just return undefined like the other files?

**Comment by sandersn** [comment]
I'd rather have a PR ready to remove them from DT first, then merge both the dt-tools PR and this PR. At least, I don't think there's any point in allowing-but-not-checking them like .npmignore et al.

**Pull request merged**
