### PR TITLE
Checks to see if the module is critically popular instead of 'not medium popular'

### PR DESCRIPTION
**Pull request by orta**
Fixes the messaging in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44437

Screen Shot 2020-05-02 at 11 49 43 AM

The module is "popular" but not critical

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Hey @orta,

Just spotted this - I read the code but I'm not super clear on what this change would result in; does it mean that the package I'm just updating would in future trigger different messages?  If so, what?

**Comment by orta** [comment]
It's just messaging - the "code reviews" section is worn "a DT maintainer will need to review it" - from the upcoming blog post:

> ### What Pull Requests Can Be Auto Merged
>
>  First up we can divide all changes to DefinitelyTyped into two major sub-groups:
>
> - PRs which add new libraries. These will always need a core team member to validate.
> - PRs which edit existing libraries. 
>
>  We can bucket changes to existing DefinitelyTyped libraries depending on their ecosystem impact:

>  - PRs which affect extremely popular libraries like Node, React, Lodash or Jest
>  - PRs which affect small to medium libraries

> Big popular libraries cannot be merged automatically and still require a team member to validate changes. 
 We quantify small to medium libraries as having less than 5,000,000 downloads per month on npm, and changes to these libraries are the bulk of the PRs we receive on the DefinitelyTyped Repo.

This was a medium library, but we were commenting as though it was an extremely big library in the middle section

**Comment by orta** [comment]
Now it says:

> Because you edited one package and updated the tests (👏), I can merge this once someone else signs off on it.

**Comment by johnnyreilly** [comment]
Nice. This is a cool automation as well - it's a great idea! 🌻

**Pull request merged**
