### PR TITLE
Removes some unused code

### PR DESCRIPTION
**Pull request by orta**
Tests and `yarn tsc` pass, so if this breaks - we've failed somewhere 🍡

### CODE REVIEW

**Review by elibarzilay — APPROVED** [review]

**Review by elibarzilay — APPROVED** [review]

**Comment by elibarzilay** [comment]
@orta: should this be merged, or maybe wait when I'm on dt so I can watch it?

**Comment by orta** [comment]
Yeah, merging then sounds good

**Comment by orta** [comment]
It's my cycle, I can handle this

**Comment by elibarzilay** [comment]
👍

**Pull request merged**
